# Generated by Django 5.2.12 on 2026-04-04 18:59

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_time', models.CharField(choices=[('lt1', '<1hr'), ('1to2', '1-2hrs'), ('2to4', '2-4hrs'), ('gt4', '4+hrs')], max_length=10)),
                ('stress_level', models.PositiveSmallIntegerField(help_text='0 (calm) to 100 (intense)')),
                ('confidence_level', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('reflection_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Check-In',
                'verbose_name_plural': 'Daily Check-Ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='reflections.dailycheckin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailycheckin',
            constraint=models.UniqueConstraint(django.db.models.functions.datetime.TruncDate('created_at'), models.F('user'), name='unique_checkin_per_user_per_day'),
        ),
    ]
