# Generated by Django 5.2.12 on 2026-04-05 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('avg_stress_level', models.FloatField(default=0)),
                ('avg_study_hours', models.FloatField(default=0)),
                ('dominant_confidence', models.CharField(default='medium', max_length=20)),
                ('total_deadlines', models.IntegerField(default=0)),
                ('completed_checkins', models.IntegerField(default=0)),
                ('user_summary', models.TextField(blank=True, default='')),
                ('ml_burnout_risk', models.CharField(blank=True, default='', max_length=20)),
                ('ml_burnout_score', models.FloatField(blank=True, null=True)),
                ('ml_stress_trend', models.CharField(blank=True, default='', max_length=20)),
                ('ml_recommendation', models.TextField(blank=True, default='')),
                ('ml_focus_areas', models.JSONField(blank=True, default=list)),
                ('ml_predicted_next_stress', models.FloatField(blank=True, null=True)),
                ('ml_wellness_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
